name             'jenkins-delivery-demo'
maintainer       'Kennon Kwok'
maintainer_email 'kennon@chef.io'
license          'all_rights'
description      'Installs/Configures jenkins-delivery-demo'
long_description 'Installs/Configures jenkins-delivery-demo'
version          '0.1.0'

depends 'apt'
depends 'packagecloud'
depends 'java'
depends 'jenkins'
depends 'docker'
depends 'chef-dk'